
name = "crypto-guard"
compatibility_date = "2023-10-30"

# Define the build output directory for Pages
[site]
bucket = "./dist"

# Set build command to avoid using build.sh directly in Pages
[build]
command = "npm run build"
