
name = "crypto-guard"
compatibility_date = "2023-10-30"

# Define the bucket directory for Cloudflare Pages
[site]
bucket = "./dist"

# Set environment variables
[vars]
NODE_VERSION = "18.17.1"

# Configure build settings
[build]
command = "npm run build"
