// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayeexcgihzbdzowqkrin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZWV4Y2dpaHpiZHpvd3FrcmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MjAxMzUsImV4cCI6MjA1NTI5NjEzNX0.0Y9QRZycaUBXGD9A3Bku0GEJD2pirqxE0xHu3omUfec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);